var exampleData1 = {
    title: 'current',
    chains : [
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx", 
            21
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyDict_DelItem", 
            3
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyFloat_FromDouble", 
            2
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyDict_Clear;PyDict_Fini", 
            1
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyObject_Call;PyType_IsSubtype;_PyObject_LookupSpecial;PyObject_Call;PyClass_IsSubclass;PyObject_Call;PyClassMethod_New;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalCodeEx;PyEval_EvalFrameEx;init_random;PyNumber_Add;PySequence_GetSlice;PyLong_FromLong", 
            3
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyInt_FromLong", 
            3
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyList_Fini", 
            2
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyObject_Realloc", 
            1
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size", 
            2
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size;PyFloat_GetMin", 
            1
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init", 
            1
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init;PyIter_Next;PySeqIter_New", 
            2
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict", 
            2
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem", 
            3
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem;PyDict_DelItem", 
            1
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;_PyType_Lookup", 
            3
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyTime_DoubleToTimet;select;__sys_select", 
            39
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random", 
            4
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random;_init", 
            4
        ], 
        [
            "0x800782a28;PyInt_FromLong", 
            1
        ], 
        [
            "strcmp", 
            1
        ]

    ]
}

var rand = function() {
    r = Math.random() + 0.1;
    return parseInt(r * r * 100);
}

var exampleData1 = {
    title: 'current',
    chains : [
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyList_Finish", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyDict_DelItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyFloat_FromDouble", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyDict_Clear;PyDict_Fini", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyObject_Call;PyType_IsSubtype;_PyObject_LookupSpecial;PyObject_Call;PyClass_IsSubclass;PyObject_Call;PyClassMethod_New;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalCodeEx;PyEval_EvalFrameEx;init_random;PyNumber_Add;PySequence_GetSlice;PyLong_FromLong", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyInt_FromLong", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyList_Fini", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyObject_Realloc", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size;PyFloat_GetMin", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init;PyIter_Next;PySeqIter_New", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem;PyDict_DelItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;_PyType_Lookup", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyTime_DoubleToTimet;select;__sys_select", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random;_init", 
            rand()
        ], 
        [
            "0x800782a28;PyInt_FromLong", 
            rand()
        ], 
        [
            "strcmp", 
            rand()
        ]

    ]
}

var exampleData2 = {
    title: 'former',
    chains : [
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyDict_DelItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyFloat_FromDouble", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyDict_Clear;PyDict_Fini", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyImport_ReloadModule;PyImport_ImportFrozenModule;PyImport_ExecCodeModuleEx;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyObject_Call;PyType_IsSubtype;_PyObject_LookupSpecial;PyObject_Call;PyClass_IsSubclass;PyObject_Call;PyClassMethod_New;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalCodeEx;PyEval_EvalFrameEx;init_random;PyNumber_Add;PySequence_GetSlice;PyLong_FromLong", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyInt_FromLong", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyList_Fini", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyObject_Realloc", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;PyTuple_Size;PyList_Size;PyFloat_GetMin", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyBuiltin_Init;PyIter_Next;PySeqIter_New", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;PyDict_GetItem;PyDict_DelItem", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyObject_GenericGetAttrWithDict;_PyType_Lookup", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;_PyTime_DoubleToTimet;select;__sys_select", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random", 
            rand()
        ], 
        [
            "0x80061b000;_start;main;Py_Main;PyRun_SimpleFileExFlags;PyRun_FileExFlags;Py_CompileString;PyEval_EvalCode;PyEval_EvalCodeEx;PyEval_EvalFrameEx;PyEval_EvalFrameEx;init_random;_init", 
            rand()
        ], 
        [
            "0x800782a28;PyInt_FromLong", 
            rand()
        ], 
        [
            "strcmp", 
            rand()
        ]
    ]
}
